{{- if and .Values.rbac.create (not .Values.rbac.namespaced) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "template.fullname" . }}-clusterrolebinding
  labels:
    {{- include "template.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "template.serviceAccountName" . }}
    namespace: {{ template "template.namespace" . }}
roleRef:
  kind: ClusterRole
{{- if (not .Values.rbac.useExistingRole) }}
  name: {{ template "template.fullname" . }}-clusterrole
{{- else }}
  name: {{ .Values.rbac.useExistingRole }}
{{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
