{{- if .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "template.fullname" . }}
  namespace: {{ template "template.namespace" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- if .Values.configMaps }}
  {{- include "common.tplvalues.render" (dict "value" .Values.configMaps "context" .) | nindent 2 }}
{{- end }}
{{- end }}



