{{- if .Values.rbac.create -}}
apiVersion: {{ template "template.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "template.fullname" . }}
  namespace: {{ template "template.namespace" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if (not .Values.rbac.useExistingRole) }}
  name: {{ template "template.fullname" . }}
{{- else }}
  name: {{ .Values.rbac.useExistingRole }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "template.serviceAccountName" . }}
  namespace: {{ template "template.namespace" . }}
{{- end -}}
